id: IEE8CAE1C
ocr_import_info:
  timestamp: '2023-06-18T17:56:26.130290+00:00'
  batch_id: batch-d599
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Peche job
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-18 22:39:03.800336+00:00
last_modified: 2023-06-18 22:39:03.800346+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1694
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1694
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསོ་རིག་རྒྱུད་བཞི། （ལྕགས་པོ་རིའི་པར་གསར།）
  languages:
  - bo
  author: གཡུ་ཐོག་གསར་མ་ཡོན་ཏན་མགོན་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8518419844399269
  ocr_word_median_confidence_index: 0.917260865
bases:
  I3CN1696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1696
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1696.txt
    statistics:
      ocr_word_median_confidence_index: 0.917260865
      ocr_word_mean_confidence_index: 0.8518419844399269
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
